### ISSUE TITLE
"Update Course" Page Frontend Fix

### ISSUE THREAD

**Issue by nlyra** [nlyra/SystemsEngineeringToolkit#122]
- Figure out how to make the front end better for the courses page (when you click on a course). 
- Some of the padding and margins are off, investigate why.

**Comment by collyntheshots** [comment]
is this still happening

**Comment by collyntheshots** [comment]
We're working in tandem on this issue, two separate solutions mine will be on branch 122-UpdateCourseInfoFrontend
